version: "3.8"

services:
  postgres:
    image: timescale/timescaledb:latest-pg17
    container_name: launchstack-postgres
    environment:
      POSTGRES_DB: launchstack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # TimescaleDB tuning for time-series workloads
      TIMESCALEDB_TUNE: "true"
      TIMESCALEDB_TUNE_MAX_CONNS: "100"
    networks:
      macvlan:
        ipv4_address: 10.1.1.82
    restart: unless-stopped
    volumes:
      - /SSD/Postgres/LaunchStack:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=timescaledb
    ports:
      - "5432:5432"

networks:
  macvlan:
    external: true 